### ISSUE TITLE
Double slash

### ISSUE THREAD

**Issue by vhernandez99** [hashlips-lab/safe-nft-metadata-provider#22] opened 2022-02-20 02:52 UTC
Giving me double slashes on the image URL

**Comment by liarco** [comment] 2022-02-20 09:22
Hi, @vhernandez99 can you please provide additional information to understand what's happening?

Thank you

**Comment by liarco** [comment] 2022-02-20 15:54
Might be duplicate of #23.

**Closed by liarco** 2022-02-20 15:54 UTC
Labels: duplicate
